export enum ActivityType {
    NAUTICAL_SPORT = 'nautical_sport',
    HIKING = 'hiking',
    COOKING_CLASS = 'cooking_class',
    CULTURAL_TOUR = 'cultural_tour',
    CYCLING = 'cycling',
    ART_CRAFT = 'art_craft',
    FOOD_AND_DRINK = 'food_and_drink',
    NATURE = 'nature',
    PHOTOGRAPHY_TOUR = 'photography_tour',
    WELLNESS = 'wellness',
    FAMILY = 'family',
    THRILL = 'thrill',
}

export type Activity = {
    id: number,
    name: string,
    type: ActivityType,
    price: number,
    lat: number,
    lng: number
}

export const activities: Activity[] = [
    { id: 1, name: "Initiation au kayak sur la côte d'Albâtre", type: ActivityType.NAUTICAL_SPORT, price: 50, lat: 49.7, lng: 0.2 },
    { id: 2, name: "Cours de voile débutant à Honfleur", type: ActivityType.NAUTICAL_SPORT, price: 70, lat: 49.41, lng: 0.23 },
    { id: 3, name: "Découverte du paddle à Deauville", type: ActivityType.NAUTICAL_SPORT, price: 60, lat: 49.36, lng: 0.08 },
    { id: 4, name: "Excursion en bateau au coucher du soleil", type: ActivityType.NAUTICAL_SPORT, price: 85, lat: 49.37, lng: 0.13 },
    { id: 5, name: "Randonnée sur les falaises d’Étretat", type: ActivityType.HIKING, price: 40, lat: 49.71, lng: 0.21 },
    { id: 6, name: "Balade nature dans la forêt de Brotonne", type: ActivityType.HIKING, price: 30, lat: 49.55, lng: 0.67 },
    { id: 7, name: "Circuit littoral Cabourg – Houlgate", type: ActivityType.HIKING, price: 35, lat: 49.28, lng: 0.14 },
    { id: 8, name: "Atelier cuisine normande à Bayeux", type: ActivityType.COOKING_CLASS, price: 55, lat: 49.28, lng: -0.70 },
    { id: 9, name: "Cours de pâtisserie au caramel beurre salé", type: ActivityType.COOKING_CLASS, price: 50, lat: 49.36, lng: 0.08 },
    { id: 10, name: "Initiation à la cuisine végétarienne", type: ActivityType.COOKING_CLASS, price: 45, lat: 49.41, lng: 0.23 },
    { id: 11, name: "Visite guidée de Bayeux et sa tapisserie", type: ActivityType.CULTURAL_TOUR, price: 20, lat: 49.28, lng: -0.69 },
    { id: 12, name: "Découverte du musée d’art moderne MuMa au Havre", type: ActivityType.CULTURAL_TOUR, price: 18, lat: 49.49, lng: 0.12 },
    { id: 13, name: "Visite guidée de la tapisserie de Bayeux et de son centre historique", type: ActivityType.CULTURAL_TOUR, price: 28, lat: 49.28, lng: -0.69 },
    { id: 14, name: "Tour à vélo sur la côte d’Albâtre", type: ActivityType.CYCLING, price: 35, lat: 49.75, lng: 0.24 },
    { id: 15, name: "Excursion VTT dans la forêt de Cerisy", type: ActivityType.CYCLING, price: 40, lat: 49.21, lng: -0.90 },
    { id: 16, name: "Balade à vélo électrique en ville à Deauville", type: ActivityType.CYCLING, price: 30, lat: 49.36, lng: 0.08 },
    { id: 17, name: "Atelier céramique artisanale", type: ActivityType.ART_CRAFT, price: 60, lat: 49.45, lng: 0.10 },
    { id: 18, name: "Stage de sculpture sur bois", type: ActivityType.ART_CRAFT, price: 70, lat: 49.48, lng: 0.11 },
    { id: 19, name: "Atelier peinture marine", type: ActivityType.ART_CRAFT, price: 50, lat: 49.52, lng: 0.23 },
    { id: 20, name: "Dégustation de fromages normands", type: ActivityType.FOOD_AND_DRINK, price: 25, lat: 49.36, lng: 0.07 },
    { id: 21, name: "Tour gastronomique de Bayeux", type: ActivityType.FOOD_AND_DRINK, price: 55, lat: 49.28, lng: -0.70 },
    { id: 22, name: "Atelier mixologie et cocktails", type: ActivityType.FOOD_AND_DRINK, price: 50, lat: 49.41, lng: 0.23 },
    { id: 23, name: "Observation des phoques au parc naturel de la Baie de Somme", type: ActivityType.NATURE, price: 40, lat: 50.12, lng: 1.60 },
    { id: 24, name: "Sortie ornithologique guidée", type: ActivityType.NATURE, price: 30, lat: 49.52, lng: 0.14 },
    { id: 25, name: "Randonnée découverte des marais de Carentan", type: ActivityType.NATURE, price: 30, lat: 49.37, lng: -0.95 },
    { id: 26, name: "Stage de photographie de paysage à Étretat", type: ActivityType.PHOTOGRAPHY_TOUR, price: 70, lat: 49.71, lng: 0.21 },
    { id: 27, name: "Balade photo urbaine à Honfleur", type: ActivityType.PHOTOGRAPHY_TOUR, price: 35, lat: 49.41, lng: 0.23 },
    { id: 28, name: "Séance de yoga sur la plage de Deauville", type: ActivityType.WELLNESS, price: 25, lat: 49.36, lng: 0.08 },
    { id: 29, name: "Massage relaxant au spa marin", type: ActivityType.WELLNESS, price: 80, lat: 49.38, lng: 0.12 },
    { id: 30, name: "Mini-golf familial à Cabourg", type: ActivityType.FAMILY, price: 20, lat: 49.28, lng: 0.15 },
    { id: 31, name: "Parc aventure enfants à Deauville", type: ActivityType.FAMILY, price: 25, lat: 49.37, lng: 0.09 },
    { id: 32, name: "Escape game familial à Bayeux", type: ActivityType.FAMILY, price: 30, lat: 49.28, lng: -0.70 },
    { id: 33, name: "Surf extrême à Siouville", type: ActivityType.THRILL, price: 60, lat: 49.38, lng: -0.39 },
    { id: 34, name: "Accrobranche et tyroliennes à Pont-Audemer", type: ActivityType.THRILL, price: 45, lat: 49.33, lng: 0.51 },
    { id: 35, name: "Parachute ascensionnel à Deauville", type: ActivityType.THRILL, price: 80, lat: 49.36, lng: 0.08 },
    { id: 36, name: "Cours de kite surf à Dieppe", type: ActivityType.NAUTICAL_SPORT, price: 90, lat: 49.92, lng: 1.08 },
    { id: 37, name: "Sortie pêche en mer à Fécamp", type: ActivityType.NAUTICAL_SPORT, price: 70, lat: 49.76, lng: 0.39 },
    { id: 38, name: "Randonnée des falaises d’Ault", type: ActivityType.HIKING, price: 35, lat: 50.12, lng: 1.55 },
    { id: 39, name: "Balade sur les sentiers de la vallée de la Seine", type: ActivityType.HIKING, price: 30, lat: 49.60, lng: 0.25 },
    { id: 40, name: "Atelier de chocolaterie à Honfleur", type: ActivityType.COOKING_CLASS, price: 60, lat: 49.41, lng: 0.23 },
    { id: 41, name: "Visite du Mémorial de Caen", type: ActivityType.CULTURAL_TOUR, price: 25, lat: 49.18, lng: -0.37 },
    { id: 42, name: "Découverte de l’architecture du Havre", type: ActivityType.CULTURAL_TOUR, price: 22, lat: 49.49, lng: 0.12 },
    { id: 43, name: "Balade vélo le long du canal de Caen", type: ActivityType.CYCLING, price: 28, lat: 49.18, lng: -0.36 },
    { id: 44, name: "Atelier vitrail à Rouen", type: ActivityType.ART_CRAFT, price: 65, lat: 49.44, lng: 1.09 },
    { id: 45, name: "Visite et dégustation cidrerie normande", type: ActivityType.FOOD_AND_DRINK, price: 30, lat: 49.31, lng: -0.55 },
    { id: 46, name: "Atelier fabrication de caramel au beurre salé", type: ActivityType.FOOD_AND_DRINK, price: 40, lat: 49.36, lng: 0.08 },
    { id: 47, name: "Observation des oiseaux au parc naturel régional des Boucles de la Seine", type: ActivityType.NATURE, price: 35, lat: 49.55, lng: 0.23 },
    { id: 48, name: "Stage photo maritime à Fécamp", type: ActivityType.PHOTOGRAPHY_TOUR, price: 60, lat: 49.76, lng: 0.39 },
    { id: 49, name: "Séance de méditation guidée en bord de mer", type: ActivityType.WELLNESS, price: 20, lat: 49.37, lng: 0.13 },
    { id: 50, name: "Atelier poterie pour enfants à Honfleur", type: ActivityType.FAMILY, price: 25, lat: 49.41, lng: 0.23 },
];
